spring:

  servlet:
    multipart:
      max-file-size: 10MB

server:
  port: 8081


app:
  image:
    upload-url: https://api.imgbb.com/1/upload?key=%s
    imgbb-key: f3d7b85ce7fca711c64ba63c15e5ecaf